/**
 * SAMPLE CODE NOTICE
 *
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Commerce.Client.ShoppingApp.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Commerce.Client.ShoppingApp.ViewModel.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AttributeDataTypeFormatBoolean {
            get {
                return ResourceManager.GetString("AttributeDataTypeFormatBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1:0.00}.
        /// </summary>
        public static string AttributeDataTypeFormatCurrency {
            get {
                return ResourceManager.GetString("AttributeDataTypeFormatCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AttributeDataTypeFormatDateTime {
            get {
                return ResourceManager.GetString("AttributeDataTypeFormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00}.
        /// </summary>
        public static string AttributeDataTypeFormatDecimal {
            get {
                return ResourceManager.GetString("AttributeDataTypeFormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AttributeDataTypeFormatInteger {
            get {
                return ResourceManager.GetString("AttributeDataTypeFormatInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string CountryRegion_CAN {
            get {
                return ResourceManager.GetString("CountryRegion_CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        public static string CountryRegion_USA {
            get {
                return ResourceManager.GetString("CountryRegion_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Enum_ProductDimensionType_Color {
            get {
                return ResourceManager.GetString("Enum_ProductDimensionType_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Enum_ProductDimensionType_Size {
            get {
                return ResourceManager.GetString("Enum_ProductDimensionType_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Enum_ProductDimensionType_Style {
            get {
                return ResourceManager.GetString("Enum_ProductDimensionType_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Enum_SalesStatus_Canceled {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Enum_SalesStatus_Confirmed {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Enum_SalesStatus_Created {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Enum_SalesStatus_Delivered {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced.
        /// </summary>
        public static string Enum_SalesStatus_Invoiced {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string Enum_SalesStatus_Lost {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Enum_SalesStatus_Processing {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Enum_SalesStatus_Sent {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Enum_SalesStatus_Unknown {
            get {
                return ResourceManager.GetString("Enum_SalesStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Enum_ToastNotificationType_Custom {
            get {
                return ResourceManager.GetString("Enum_ToastNotificationType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Enum_ToastNotificationType_Error {
            get {
                return ResourceManager.GetString("Enum_ToastNotificationType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Enum_ToastNotificationType_Info {
            get {
                return ResourceManager.GetString("Enum_ToastNotificationType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Enum_ToastNotificationType_Success {
            get {
                return ResourceManager.GetString("Enum_ToastNotificationType_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Enum_ToastNotificationType_Warning {
            get {
                return ResourceManager.GetString("Enum_ToastNotificationType_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MainTabs_Account {
            get {
                return ResourceManager.GetString("MainTabs_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string MainTabs_Cart {
            get {
                return ResourceManager.GetString("MainTabs_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string MainTabs_Products {
            get {
                return ResourceManager.GetString("MainTabs_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string MenuPage_Products {
            get {
                return ResourceManager.GetString("MenuPage_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright .
        /// </summary>
        public static string Pages_AboutPage_CopyRightInfo {
            get {
                return ResourceManager.GetString("Pages_AboutPage_CopyRightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Pages_AboutPage_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Pages_AboutPage_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License terms.
        /// </summary>
        public static string Pages_AboutPage_TermsOfUse {
            get {
                return ResourceManager.GetString("Pages_AboutPage_TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party notices.
        /// </summary>
        public static string Pages_AboutPage_ThirdPartyNotices {
            get {
                return ResourceManager.GetString("Pages_AboutPage_ThirdPartyNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Pages_AboutPage_Title {
            get {
                return ResourceManager.GetString("Pages_AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.0.0.0.
        /// </summary>
        public static string Pages_AboutPage_VersionNumber {
            get {
                return ResourceManager.GetString("Pages_AboutPage_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Pages_AccountPage_About {
            get {
                return ResourceManager.GetString("Pages_AccountPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Pages_AccountPage_AccountInformation {
            get {
                return ResourceManager.GetString("Pages_AccountPage_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation mode settings.
        /// </summary>
        public static string Pages_AccountPage_EvaluationModeSettings {
            get {
                return ResourceManager.GetString("Pages_AccountPage_EvaluationModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Pages_AccountPage_OrderHistory {
            get {
                return ResourceManager.GetString("Pages_AccountPage_OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Pages_AccountPage_SignIn {
            get {
                return ResourceManager.GetString("Pages_AccountPage_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Pages_AccountPage_SignOut {
            get {
                return ResourceManager.GetString("Pages_AccountPage_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Pages_CardPaymentPage_Done {
            get {
                return ResourceManager.GetString("Pages_CardPaymentPage_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string Pages_CardPaymentPage_Title {
            get {
                return ResourceManager.GetString("Pages_CardPaymentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is currently empty..
        /// </summary>
        public static string Pages_CartPage_CartIsEmpty {
            get {
                return ResourceManager.GetString("Pages_CartPage_CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add products to the shopping cart to checkout..
        /// </summary>
        public static string Pages_CartPage_CartIsEmptyMessage {
            get {
                return ResourceManager.GetString("Pages_CartPage_CartIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid quantity..
        /// </summary>
        public static string Pages_CartPage_CartLineQuantityUpdateErrorMessage {
            get {
                return ResourceManager.GetString("Pages_CartPage_CartLineQuantityUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity has been updated for {0}.
        /// </summary>
        public static string Pages_CartPage_CartLineQuantityUpdateSuccessMessage {
            get {
                return ResourceManager.GetString("Pages_CartPage_CartLineQuantityUpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to checkout.
        /// </summary>
        public static string Pages_CartPage_Checkout {
            get {
                return ResourceManager.GetString("Pages_CartPage_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Pages_CartPage_Delete {
            get {
                return ResourceManager.GetString("Pages_CartPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total product lines: .
        /// </summary>
        public static string Pages_CartPage_ItemCount {
            get {
                return ResourceManager.GetString("Pages_CartPage_ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Pages_CartPage_Quantity_Abbreviation {
            get {
                return ResourceManager.GetString("Pages_CartPage_Quantity_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string Pages_CartPage_Savings {
            get {
                return ResourceManager.GetString("Pages_CartPage_Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Pages_CartPage_SubTotalAmount {
            get {
                return ResourceManager.GetString("Pages_CartPage_SubTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string Pages_CartPage_Title {
            get {
                return ResourceManager.GetString("Pages_CartPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total savings.
        /// </summary>
        public static string Pages_CartPage_TotalDiscount {
            get {
                return ResourceManager.GetString("Pages_CartPage_TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string Pages_CartPage_ValidationFailed {
            get {
                return ResourceManager.GetString("Pages_CartPage_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Pages_CategoryListPage_Products {
            get {
                return ResourceManager.GetString("Pages_CategoryListPage_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide all the required details (Name, Street, City, State, Zipcode, Email).
        /// </summary>
        public static string Pages_CheckoutAddressPage_AddressIsEmptyMessage {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_AddressIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Pages_CheckoutAddressPage_AddressLine {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Pages_CheckoutAddressPage_City {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email address.
        /// </summary>
        public static string Pages_CheckoutAddressPage_ConfirmEmail {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Pages_CheckoutAddressPage_Continue {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Pages_CheckoutAddressPage_CountryPickerTitle {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_CountryPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not signed up as a customer. You have been signed out and will check out as guest..
        /// </summary>
        public static string Pages_CheckoutAddressPage_CustomerNotSignedUp {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_CustomerNotSignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery options cannot be found. Check your address (e.g., State code) and try again..
        /// </summary>
        public static string Pages_CheckoutAddressPage_DeliveryOption_Error {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_DeliveryOption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Pages_CheckoutAddressPage_Email {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses do not match..
        /// </summary>
        public static string Pages_CheckoutAddressPage_EmailNotEqual_Error {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_EmailNotEqual_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Pages_CheckoutAddressPage_EmailNotValid_Error {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_EmailNotValid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping name.
        /// </summary>
        public static string Pages_CheckoutAddressPage_Name {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State (Two letter code e.g. WA).
        /// </summary>
        public static string Pages_CheckoutAddressPage_State {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only two letter state code (e.g. WA) is allowed..
        /// </summary>
        public static string Pages_CheckoutAddressPage_StateCodeInvalidFormat {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_StateCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Pages_CheckoutAddressPage_Title {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update existing address.
        /// </summary>
        public static string Pages_CheckoutAddressPage_Update_Address {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_Update_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save your primary address for next checkout..
        /// </summary>
        public static string Pages_CheckoutAddressPage_UpdatePrimaryAddress_Error {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_UpdatePrimaryAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string Pages_CheckoutAddressPage_ValidationFailed {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string Pages_CheckoutAddressPage_ZipCode {
            get {
                return ResourceManager.GetString("Pages_CheckoutAddressPage_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Pages_CheckoutDeliveryOptionsPage_Continue {
            get {
                return ResourceManager.GetString("Pages_CheckoutDeliveryOptionsPage_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a shipping option.
        /// </summary>
        public static string Pages_CheckoutDeliveryOptionsPage_Label {
            get {
                return ResourceManager.GetString("Pages_CheckoutDeliveryOptionsPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Delivery Option.
        /// </summary>
        public static string Pages_CheckoutDeliveryOptionsPage_PickerTitle {
            get {
                return ResourceManager.GetString("Pages_CheckoutDeliveryOptionsPage_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Options.
        /// </summary>
        public static string Pages_CheckoutDeliveryOptionsPage_Title {
            get {
                return ResourceManager.GetString("Pages_CheckoutDeliveryOptionsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your purchase. Your order number is {0}..
        /// </summary>
        public static string Pages_CheckoutPage_Cart_OrderResultMessage {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_Cart_OrderResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string Pages_CheckoutPage_CreditCard {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide credit card information.
        /// </summary>
        public static string Pages_CheckoutPage_PaymentDetails {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide all the required details before placing the order..
        /// </summary>
        public static string Pages_CheckoutPage_Place_Order_Error {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_Place_Order_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string Pages_CheckoutPage_PlaceOrder {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shipping address.
        /// </summary>
        public static string Pages_CheckoutPage_SelectShipping {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_SelectShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping option.
        /// </summary>
        public static string Pages_CheckoutPage_ShippingOption {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_ShippingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Pages_CheckoutPage_Title {
            get {
                return ResourceManager.GetString("Pages_CheckoutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card payment host page URL.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_CardPaymentHostPageUrl {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_CardPaymentHostPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data service URL.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_DataServiceUrl {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_DataServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media base URL.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_MediaBaseUrl {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_MediaBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating unit number for online channel.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_OperatingUnitNumber {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_OperatingUnitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Operating Unit Number for online channel.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_OperatingUnitNumberErrorMessage {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_OperatingUnitNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid URL.
        /// </summary>
        public static string Pages_EvaluationModeSettingsPage_UrlErrorMessage {
            get {
                return ResourceManager.GetString("Pages_EvaluationModeSettingsPage_UrlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso.
        /// </summary>
        public static string Pages_MenuPage_AppName {
            get {
                return ResourceManager.GetString("Pages_MenuPage_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string Pages_OrderDetailsPage_CreatedDateTime {
            get {
                return ResourceManager.GetString("Pages_OrderDetailsPage_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string Pages_OrderDetailsPage_SalesId {
            get {
                return ResourceManager.GetString("Pages_OrderDetailsPage_SalesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        public static string Pages_OrderDetailsPage_StatusValue {
            get {
                return ResourceManager.GetString("Pages_OrderDetailsPage_StatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order detail.
        /// </summary>
        public static string Pages_OrderDetailsPage_Title {
            get {
                return ResourceManager.GetString("Pages_OrderDetailsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order total.
        /// </summary>
        public static string Pages_OrderDetailsPage_TotalAmount {
            get {
                return ResourceManager.GetString("Pages_OrderDetailsPage_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not signed up as a customer. Sign up as a customer and try again..
        /// </summary>
        public static string Pages_OrderHistoryPage_CustomerNotSignedUp {
            get {
                return ResourceManager.GetString("Pages_OrderHistoryPage_CustomerNotSignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        public static string Pages_ProductDescriptionPage_Title {
            get {
                return ResourceManager.GetString("Pages_ProductDescriptionPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Pages_ProductDetail_AddToCart {
            get {
                return ResourceManager.GetString("Pages_ProductDetail_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all required options (size, color, style) and try again..
        /// </summary>
        public static string Pages_ProductPage_AddToCartError {
            get {
                return ResourceManager.GetString("Pages_ProductPage_AddToCartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Pages_ProductPage_PriceLabel {
            get {
                return ResourceManager.GetString("Pages_ProductPage_PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added to cart..
        /// </summary>
        public static string Pages_ProductPage_ProductDetail_AddToCartMessage {
            get {
                return ResourceManager.GetString("Pages_ProductPage_ProductDetail_AddToCartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a {0}.
        /// </summary>
        public static string Pages_ProductPage_ProductDetails_PickerTitle {
            get {
                return ResourceManager.GetString("Pages_ProductPage_ProductDetails_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Products.
        /// </summary>
        public static string Pages_ProductSearchPage_SearchBar_Placeholder {
            get {
                return ResourceManager.GetString("Pages_ProductSearchPage_SearchBar_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        public static string Pages_SignInPage_GoogleSignIn {
            get {
                return ResourceManager.GetString("Pages_SignInPage_GoogleSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Pages_SignInPage_SignIn_Title {
            get {
                return ResourceManager.GetString("Pages_SignInPage_SignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string Separator_String {
            get {
                return ResourceManager.GetString("Separator_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is currently not available. Check your network connection and try again later..
        /// </summary>
        public static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is currently not available. Check your evaluation mode settings and network connection, and try again later..
        /// </summary>
        public static string ServiceNotAvailableEvaluationMode {
            get {
                return ResourceManager.GetString("ServiceNotAvailableEvaluationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address.
        /// </summary>
        public static string Views_AddressLabelView_ShippingAddress {
            get {
                return ResourceManager.GetString("Views_AddressLabelView_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected credit card type is not supported..
        /// </summary>
        public static string Views_CardPaymentView_CardTypeNotSupported {
            get {
                return ResourceManager.GetString("Views_CardPaymentView_CardTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Views_CartToolBarItem_Cart {
            get {
                return ResourceManager.GetString("Views_CartToolBarItem_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Views_OrderLinesView_Quantity_Abbreviation {
            get {
                return ResourceManager.GetString("Views_OrderLinesView_Quantity_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string Views_OrderLinesView_Savings {
            get {
                return ResourceManager.GetString("Views_OrderLinesView_Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping and handling.
        /// </summary>
        public static string Views_OrderSummaryView_EstimatedShippingAmount {
            get {
                return ResourceManager.GetString("Views_OrderSummaryView_EstimatedShippingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Views_OrderSummaryView_SubTotalAmount {
            get {
                return ResourceManager.GetString("Views_OrderSummaryView_SubTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Views_OrderSummaryView_TaxAmount {
            get {
                return ResourceManager.GetString("Views_OrderSummaryView_TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order total.
        /// </summary>
        public static string Views_OrderSummaryView_TotalAmount {
            get {
                return ResourceManager.GetString("Views_OrderSummaryView_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total savings.
        /// </summary>
        public static string Views_OrderSummaryView_TotalDiscount {
            get {
                return ResourceManager.GetString("Views_OrderSummaryView_TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Views_SearchToolBarItem_Search {
            get {
                return ResourceManager.GetString("Views_SearchToolBarItem_Search", resourceCulture);
            }
        }
    }
}
